Moved Makefile and updated workflow

diff --git a/jlox/Makefile b/jlox/Makefile
--- a/jlox/Makefile
+++ b/jlox/Makefile
@@ -1,8 +1,9 @@
 JAVAC = javac
 JAVA = java
-SRC_DIR = jlox
-TOOLS_DIR = tools
+SRC_DIR = .
+TOOLS_DIR = ../tools
 BIN_DIR = bin
+TESTS_DIR = ../tests
 MAIN_CLASS = jlox.Lox
 
 all: build tools
@@ -22,7 +23,17 @@ gen: tools
 	@$(JAVA) -cp $(BIN_DIR) $(TOOLS_DIR).GenerateAst $(SRC_DIR)
 
 test: build
-	@for file in tests/*.lox; do echo -n "Testing file $$file  " ; $(MAKE) -s run ARGS="$$file" && echo -e "\x1b[32mPassed !\x1b[37m"; done
+	@failed=0; \
+	for file in $(TESTS_DIR)/*.lox; do \
+		echo -n "Testing file $$file  "; \
+		if $(MAKE) -s run ARGS="$$file"; then \
+			echo -e "\x1b[32mPassed !\x1b[37m"; \
+		else \
+			echo -e "\x1b[31mFailed !\x1b[37m"; \
+			failed=1; \
+		fi; \
+	done; \
+	exit $$failed
 	
 clean:
 	@rm -rf $(BIN_DIR)
